{
 "title": "My Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "traces_span_metrics_duration_milliseconds_bucket"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "System Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod CPU %",
   "type": "timeseries",
   "description": "This is the percentage of CPU usage by pod. Total core cpu is 4+4+4 = 12 core",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{namespace=\"otel-demo\"}[5m])) by (pod) / scalar(sum(machine_cpu_cores))\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory Usage (GB)",
   "type": "timeseries",
   "description": "The total Memory is 48 GB",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace=\"otel-demo\" , pod!=\"\"} \r\n) / 1024 / 1024 / 1024 \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "the average number of new requests per second in 5 minutes ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (service_route) (\r\n  label_join(\r\n    label_replace(\r\n      rate(http_server_request_duration_seconds_sum{service_name=~\"$service\"}[5m]),\r\n      \"short_http_route\",\r\n      \"$1\",\r\n      \"http_route\",\r\n      \".*/([^/]+)$\"\r\n    ),\r\n    \"service_route\",\r\n    \"/\",\r\n    \"service_name\",\r\n    \"short_http_route\"\r\n  )\r\n)\r\n",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Error Rate by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(service_name) ( \r\n  rate(traces_span_metrics_calls_total{service_name=~\"$service\",status_code=\"STATUS_CODE_ERROR\"}[5m]) \r\n) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency in ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (service_route) (\r\n  label_join(\r\n    label_replace(\r\n      rate(http_server_request_duration_seconds_sum{service_name=~\"$service\"}[5m]),\r\n      \"short_http_route\",\r\n      \"$1\",\r\n      \"http_route\",\r\n      \".*/([^/]+)$\"  #taking the last segment of http_route\r\n    ),\r\n    \"service_route\",\r\n    \"/\",\r\n    \"service_name\",\r\n    \"short_http_route\"\r\n  )\r\n) / sum by (service_route) (\r\n  label_join(\r\n    label_replace(\r\n      rate(http_server_request_duration_seconds_count[5m]),\r\n      \"short_http_route\",\r\n      \"$1\",\r\n      \"http_route\",\r\n      \".*/([^/]+)$\"\r\n    ),\r\n    \"service_route\",\r\n    \"/\",\r\n    \"service_name\",\r\n    \"short_http_route\"\r\n  )\r\n) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Duration by Span Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=~\"${service}\"}[$__rate_interval])) by (le, span_name))",
     "legendFormat": "{{ span_name }}"
    }
   ]
  },
  {
   "title": "Active request numbers",
   "type": "gauge",
   "description": "Requests currently being processed\nInstantaneous",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service_route) (\r\n  label_join(\r\n    label_replace(\r\n      http_server_active_requests{service_name=~\"$service\"},\r\n      \"short_http_route\",\r\n      \"$1\",\r\n      \"http_route\",\r\n      \".*/([^/]+)$\"\r\n    ),\r\n    \"service_route\",\r\n    \"/\",\r\n    \"service_name\",\r\n    \"short_http_route\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  { "title": "Application Log Record", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Log Records by Severity",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 35 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "observedTimestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "search source=otel\r\n| where resource.service.name=\"${service}\"\r\n| stats count() by severity.text",
     "timeField": "observedTimestamp"
    }
   ]
  },
  {
   "title": "Log Records (Last 100)",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 35 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "observedTimestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "search source=otel\r\n| where resource.service.name=\"${service}\"\r\n| sort - observedTimestamp \r\n| head 100",
     "timeField": "observedTimestamp"
    }
   ]
  },
  { "title": "Service Dependency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Service Dependency",
   "type": "nodeGraph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  }
 ]
}